# Generated by Django 4.0.2 on 2022-03-26 06:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_message_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
